# Workflows and Styles

No project will perfectly fit a standard mold, but aiming to follow a general set of methods makes it easier to collaborate in code development and maintain code products.

## Project Organization

-   note function for new project folder prep

-   recommend renv

## Data Style

-   all caps column names

-   neverstart with numbers; if numbers use leading zeros for alphanumeric sort

-   if dates, always yyyy-mm-dd

## Code Style

-   generally Tidyverse (provide link to tidyverse style resources; offer kdv lintr as a resource, recommend settings in RStudio)

-   with some exceptions (list main exceptions)

-   general value of readability/accessibility/reproducibility over efficiency  - unless working with very large data where nanoseconds saved in efficiency add up to hours

-   unless otherwise specified, always theme_bw(), always centered title - note existence of KDV color palettes and ggplot theme

## 508 Compliance

-   always recommend to clients and always do as much as feasible within scope of budget

-   give quick summary of what it is and a link to one or two online tools that can review code (preferably without storing it - there are some, I think)

-   minimum KDV requirements: colorblind friendly palettes (link to recommended palettes in R), include alt text (link to tips of writing good alt text?), correct use of headers for organization instead of style - define css classes for special styles

## Methods in Git

-   large projects with multiple milestones are managed in a more "gitflow" style; small projects with single deliverable skip the dev branch

-   all client projects are private repos, unless (or until) otherwise stated

-   internal vs external collaborators - internal all work from same repo, external fork and develop on their version

-   privide link to some basic gitflow resources and the gitgames

-   we use organizational github for our repos, recommend free Fork software as a branch visualization and management tool, recommend Jenny Bryan git with r online textbook as a linked resource
